doc/mlsys_paper/paper.tex

starting point for the abstract. needs sharpening and more meat (eg. need to explicitly state the speedups from the experiments).

first stab at the abstract

---

doc/mlsys_paper/paper.tex

proposed title: "ensmallen: a flexible C++ library for efficient function optimization"
I've added "efficient" for two reasons:
(a) suggests that it's "better"/"faster" than other approaches
(b) the words "function optmization" are now together on a separate line within the title (much cleaner look)

title candidate

---

doc/mlsys_paper/paper.bib

Various fixes, including captialisation, more details for publication venues, author order.
Also shortened a few references to improve appearance.

fixes for references

---

doc/mlsys_paper/paper.tex

Improvements and suggestions for further details in section 4 (Available Optimizers).
See the embedded notes/comments for more details.

section 4: improvements and suggestions for further details

---

doc/mlsys_paper/paper.tex

Clarifications, sharpening and defluffing for section 2 (Types of objective functions).
I've also added notes on where further edits are probably required.

section 2: clarifications, sharpening and defluffing

---

doc/mlsys_paper/paper.tex

Minor rewrites and suggestions for further improvements in section 3 (Example: Learning Linear Regression Models).
See the embedded notes/comments for more details.

section 3: minor rewrites and suggestions for further improvements

---

include/ensmallen_bits/ens_version.hpp

"Corporate Catabolism"
https://en.wiktionary.org/wiki/catabolism

bump to version 1.10; proposed name

---

doc/mlsys_paper/nips_2018.sty
doc/mlsys_paper/paper.tex

- remove the blank line before argmin on the first page, as this causes really ugly layout and spoils the continuity of the bullet point list on page two
- fix misuse of href in the conclusion

fix layout problems and href bug

---

.travis.yaml

Travis config to automatically run the test suite.

travis ci config

---

include/ensmallen_bits/sgd/decay_policies/no_decay.hpp
include/ensmallen_bits/sgd/sgd.hpp
include/ensmallen_bits/sgd/sgd_impl.hpp
include/ensmallen_bits/sgd/update_policies/nesterov_momentum_update.hpp

Reinclude the logging mechanism for the SGD optimizer.

Reinclude logging (SGD optimizer)

---

doc/README.md
doc/function_types.md
doc/optimizers.md

We can store the documentation in this repository.
Next, I'll redo the website so it automatically grabs documentation out of the most recent version of ensmallen to generate the pages.

Add documentation that's used to make the website.

---

include/ensmallen.hpp
include/ensmallen_bits/grid_search/grid_search_impl.hpp
tests/CMakeLists.txt
tests/grid_search_test.cpp

I noticed that there were a few bugs in the implementation and that it wasn't included by default.
I wrote and added a test for it also.

Fix and include GridSearch by default

---

include/ensmallen_bits/function/sfinae_utility.hpp

Avoid redefinition of SigCheck.

Redefinition SigCheck

---

HISTORY.md
doc/function_types.md

This fixes #52.
Once this is merged I'll go ahead and release 1.11.0.

Header documentation fix

---

doc/optimizers.md

I just used what was in swats.hpp to create a block for `optimizers.md`.

Add documentation for SWATS.

---

include/ensmallen_bits/spsa/spsa.hpp

Fix reorder warning see #74 for more information.

Fix reorder warning

---

HISTORY.md
doc/optimizers.md

I found these while reviewing different optimization papers.

Minor documentation fixes.

---

.github/ISSUE_TEMPLATE/0-bug.md
.github/ISSUE_TEMPLATE/1-documentation.md
.github/ISSUE_TEMPLATE/2-question.md

These are just the same ones from the mlpack repository, slightly adapted where necessary.

Add issue templates.

---

tests/spsa_test.cpp

This should fail less than ~1 in 1000 times.
Thanks to @SuryodayBasak and @favre49 for pointing this out in IRC. :+1:

Adjust tolerances for SPSA test.

---

doc/function_types.md
doc/optimizers.md

- fix errant â€“ characters
- fix internal links for differentiable separable functions

documentation fixes

---

include/ensmallen_bits/fw/atoms.hpp

add arma:: prefix to size(x)
see https://github.com/mlpack/ensmallen/issues/110

workaround for MSVC bug

---

HISTORY.md

Addresses #122.  @coatless let me know if this is what you were thinking or if you had something else in mind. :)

Add version names and use Markdown links in HISTORY.md

---

HISTORY.md
include/ensmallen_bits/pso/pso.hpp

Looks like this one was an issue also.  Once this is merged I'll make a bugfix release.

Fix incorrect return type for PSO.

---

doc/callbacks.md

Switch mlpack with ensmallen in callback docs

---

HISTORY.md
include/ensmallen_bits/config.hpp
include/ensmallen_bits/parallel_sgd/parallel_sgd_impl.hpp
tests/parallel_sgd_test.cpp

Fix for the test timeout seen here: http://ci.mlpack.org/view/ensmallen/job/docker%20ensmallen%20nightly%20build/

ParallelSGD omp fix

---

doc/function_types.md

While digging around, I noticed that there were a few optimizer types missing from the documentation for different types of functions.  This PR fixes that. :)

Add some missing optimizer types.

---

README.md

Signed-off-by: Omar Shrit <shrit@lri.fr>

Adding bib tex format in the README

---

.travis.yml
HISTORY.md
scripts/history-update-check.sh

I'm honestly not sure exactly why the @coatless method didn't work (#171 #172 ), but this is my attempt to fix it.

Re-fix Ensmallen History Mod Checker

---

COPYRIGHT.txt
HISTORY.md
doc/function_types.md
include/ensmallen_bits/sdp/primal_dual.hpp
include/ensmallen_bits/sdp/primal_dual_impl.hpp
tests/sdp_primal_dual_test.cpp

remove sdp deprecated methods

---

HISTORY.md
include/ensmallen_bits/function/arma_traits.hpp
include/ensmallen_bits/utility/arma_traits.hpp

similar to the recent fix in mlpack: https://github.com/mlpack/mlpack/pull/2356

handle SpSubview_col and SpSubview_row in Armadillo 9.870

---

CONTRIBUTING.md
HISTORY.md
include/ensmallen_bits/ens_version.hpp
scripts/ensmallen-release.sh

This automatically-generated pull request adds the commits necessary to make the 2.12.1 release.

Release version 2.12.1

---

HISTORY.md
scripts/ensmallen-release.sh
scripts/update-website-after-release.sh

Everything worked pretty well (but not perfectly) for the automatic 2.13.0 release.  This fixes some simple bugs I found in the website update script.

Website update release script fixes

---

CONTRIBUTING.md
HISTORY.md
include/ensmallen_bits/ens_version.hpp

This automatically-generated pull request adds the commits necessary to make the 2.14.0 release.
* Add NSGA2 optimizer for multi-objective functions
([#149](https://github.com/mlpack/ensmallen/pull/149)).
* Update automatic website update release script
([#207](https://github.com/mlpack/ensmallen/pull/207)).
* Clarify and fix documentation for constrained optimizers
([#201](https://github.com/mlpack/ensmallen/pull/201)).
* Fix L-BFGS convergence when starting from a minimum
([#201](https://github.com/mlpack/ensmallen/pull/201)).

Release version 2.14.0: "No Direction Home"

---

CONTRIBUTING.md
HISTORY.md
include/ensmallen_bits/ens_version.hpp

This automatically-generated pull request adds the commits necessary to make the 2.14.2 release.
* Fix implementation of fonesca fleming problem function f1 and f2  type usage and negative signs. ([#223](https://github.com/mlpack/ensmallen/pull/223))

Release version 2.14.2: "No Direction Home"

---

doc/callbacks.md
include/ensmallen_bits/callbacks/store_best_coordinates.hpp

I am not sure if it is an error. Logically both of the functions should have the same name.
Signed-off-by: Omar Shrit <omar@shrit.me>

Fix a bug in the function name

---

HISTORY.md
scripts/ensmallen-release.sh

I mean, this is not a very substantive pull request.  But, it would display wrong before... :)

Make sure there's a space in release script output

---

CONTRIBUTING.md
HISTORY.md
include/ensmallen_bits/ens_version.hpp

This automatically-generated pull request adds the commits necessary to make the 2.16.0 release.
* Expand README with example installation and add simple example program showing usage of the L-BFGS optimizer ([#248](https://github.com/mlpack/ensmallen/pull/248)).
* Refactor tests to increase stability and reduce random errors ([#249](https://github.com/mlpack/ensmallen/pull/249)).

Release version 2.16.0: "Severely Dented Can Of Polyurethane"

---

include/ensmallen_bits/cmaes/cmaes.hpp

Fix CMAES population size parameter comment

---

HISTORY.md

@rcurtin  Yo, continuing the work from the tagged PR since it was closed.
Related PR: #297.

Modify HISTORY.md release history

---

HISTORY.md
include/ensmallen_bits/problems/zdt/zdt4_function.hpp

ZDT4 Evaluate Fix

---

include/ensmallen_bits/nsga2/nsga2.hpp
include/ensmallen_bits/nsga2/nsga2_impl.hpp

No change in speed, but I guess lower LoC is good? @zoq  Skipping HISTORY.md

Reduce LOC of NSGA-II

---

include/ensmallen_bits/moead/decomposition_policies/pbi_decomposition.hpp
include/ensmallen_bits/moead/moead_impl.hpp

Let's keep this open while I fix MOEAD entirely 🔧.

Repair MOEAD

---

README.md

corresponding website changes also proposed in https://github.com/mlpack/ensmallen.org/pull/12

update citation to JMLR paper

---

CITATION.cff

Add citation file to use GitHub's citation feature.

Add citation file.

---

HISTORY.md
tests/catch.hpp

See https://github.com/mlpack/ensmallen/issues/321 for more details.

Update Catch2 to 2.13.7

---

HISTORY.md
tests/sgd_test.cpp

Accelerate SGD test time by skipping additional trials.

Accelerate SGD test time by skipping additional trials.

---

HISTORY.md
include/ensmallen.hpp

bump check for min supported version of armadillo

---

CONTRIBUTING.md
HISTORY.md
include/ensmallen_bits/ens_version.hpp

This automatically-generated pull request adds the commits necessary to make the 2.19.0 release.
* Added DemonSGD and DemonAdam optimizers ([#211](https://github.com/mlpack/ensmallen/pull/211)).
* Fix bug with Adam-like optimizers not resetting when `resetPolicy` is `true`. ([#340](https://github.com/mlpack/ensmallen/pull/340)).
* Add Yogi optimizer ([#232](https://github.com/mlpack/ensmallen/pull/232)).
* Add AdaBelief optimizer ([#233](https://github.com/mlpack/ensmallen/pull/233)).
* Add AdaSqrt optimizer …

Release version 2.19.0: "Eight Ball Deluxe"

---

.appveyor.yml

Windows build fix

---

tests/catch.hpp

upgrade to Catch v2.13.10

---

HISTORY.md

I just noticed this while poking through.

Remove duplicate HISTORY.md entry

---

CMakeLists.txt
HISTORY.md

Ensure the tests are built with optimisation enabled.   Otherwise the tests take forever to run.

ensure the tests are built with optimisation enabled

---

tests/catch.hpp

adapted from upstream catch2 repo: https://github.com/catchorg/Catch2/pull/2840

catch2 workaround for recent issue under macOS

---

HISTORY.md

fix HISTORY.md
