- doc/mlsys_paper/paper.tex
Remove those super-ugly link boxes and replace them with sane looking links.  This noticeably improves the presentation of the paper (ie. less annoying for reviewers).
> fix the default super-ugly coloured link boxes (citations, urls, figure numbers, footnote numbers, etc)

- doc/mlsys_paper/paper.tex
Clarifications and sharpening for section 6 (Automatic Generation of Methods).
I suggest moving a subset of the text from the problematic "Templates for speed" section to this section.
> section 6: clarifications and sharpening

- doc/mlsys_paper/paper.tex
Clarifications, sharpening and notes for further improvements for section 7 (Experiments).
This section still needs work.  I'm not convinced that the "we do inlining" conjecture is barking up the right tree.  (This ties in with section 5 being rather weak and unconvincing).
SciPy is in Python, which is by default an interpreted language. The slowdown in Python many have nothing to do with inlining and simply due to Python being slow in general. It's possible to use PyPy or Numba to speed things up, in order to provide a "fairer" comparison against compiled languages. Octave also has an optional JIT compiler, which last time I checked needs to be explicitly enabled.
I would suggest to stay away from the "we do inlining" argument, as it can be blown up too easily. Furthermore, I would …
> section 7: clarifications, sharpening and notes for further improvements

- doc/optimizers.md
- include/ensmallen.hpp
- include/ensmallen_bits/ftml/ftml.hpp
- include/ensmallen_bits/ftml/ftml_impl.hpp
- include/ensmallen_bits/ftml/ftml_update.hpp
Implementation of "Follow the Moving Leader in Deep Learning" by Shuai Zheng and James T. Kwok.
> FTML optimizer

- include/ensmallen.hpp
- include/ensmallen_bits/swats/swats.hpp
- include/ensmallen_bits/swats/swats_impl.hpp
- include/ensmallen_bits/swats/swats_update.hpp
- tests/CMakeLists.txt
- tests/swats_test.cpp
Implementation of "Improving Generalization Performance by Switching from Adam to SGD" by Nitish Shirish Keskar and Richard Socher.
> SWATS optimizer

- doc/function_types.md
Fix for a small error in the documentation where ens::RMSProp was being used.
If this same file is being used on the website for the documentation, then this should fix the issue there too. Else, the same error is there on the documentation webpage.
> Incorrect class name RMSProp in documentation

- doc/optimizers.md
- include/ensmallen_bits/aug_lagrangian/aug_lagrangian.hpp
- include/ensmallen_bits/aug_lagrangian/aug_lagrangian_impl.hpp
- include/ensmallen_bits/sdp/lrsdp_impl.hpp
- tests/CMakeLists.txt
- tests/aug_lagrangian_test.cpp
Added optionality to set the L-BFGS iterations, the penalty update factor and the sigma update factor in the augmented Lagrangian class. Kept defaults the same as the originally hardcoded values.
> Added Augmented Lagrangian options

- doc/function_types.md
- doc/optimizers.md
- include/ensmallen.hpp
- include/ensmallen_bits/cmaes/cmaes_impl.hpp
- include/ensmallen_bits/de/de.hpp
- include/ensmallen_bits/de/de_impl.hpp
- tests/de_test.cpp
This is a best/1/bin implementation of Differential Evolution
> Differential Evolution

- HISTORY.md
- doc/function_types.md
- doc/optimizers.md
- include/ensmallen_bits/spsa/spsa.hpp
- include/ensmallen_bits/spsa/spsa_impl.hpp
- tests/spsa_test.cpp
Adjust SPSA Logistic Regression test optimizer parameter.
> Adjust SPSA Logistic Regression test optimizer parameter

- HISTORY.md
- doc/optimizers.md
- include/ensmallen_bits/cne/cne.hpp
- include/ensmallen_bits/cne/cne_impl.hpp
- include/ensmallen_bits/de/de.hpp
- include/ensmallen_bits/de/de_impl.hpp
- tests/cne_test.cpp
- tests/de_test.cpp
For CNE, i generated the population around the given starting point, which made it run in 1/6th of the time it took before on the Logistic regression test
For DE, i realized my implementation lacked termination for tolerance and objective change, which made it run for far far longer than it needed to. It now completes the logistic regression test in less than a second.
I also made the necessary documentation changes
> Optimized CNE and DE

- HISTORY.md
- include/ensmallen_bits/sgdr/cyclical_decay.hpp
It had two titles... not sure how that happened. :)
> `cyclical_decay.hpp` BibTeX fix

- include/ensmallen_bits/sdp/primal_dual_impl.hpp
- tests/sdp_primal_dual_test.cpp
if we assume arma::eig_sym() succeeds, but in fact it fails, accessing elements in the evals vector will result either in a crash or an out-of-bounds error.
> fix: don't assume that arma::eig_sym() always succeeds

- include/ensmallen_bits/bigbatch_sgd/adaptive_stepsize.hpp
- include/ensmallen_bits/bigbatch_sgd/backtracking_line_search.hpp
- include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd_impl.hpp
> Rectified Big Batch SGD implementation

- HISTORY.md
- doc/optimizers.md
- include/ensmallen_bits/qhadam/qhadam_update.hpp
- include/ensmallen_bits/spsa/spsa.hpp
- include/ensmallen_bits/spsa/spsa_impl.hpp
Addresses the variable initialization issue highlighted under -Wreorder, c.f.
```
../inst/include/ensmallen_bits/qhadam/qhadam_update.hpp:57:5: 
warning: field 'v2' will be initialized after field 'iteration' [-Wreorder]
```
@rcurtin + @zoq  I can tackle #114 if need be in this as well.
> Fix compilation warnings

- .travis.yml
- CMakeLists.txt
When building ensmallen on TravisCI, verify the code passes traditional ISO checks given by:
```
-Wall -Wpedantic -Wextra
```
If not, treat any warnings that arise as errors with `-Werror`. Show the errors clearly by colorizing the diagnostic output using `-fdiagnostics-color`.
These checks are generally used by CRAN:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-portable-packages
> Enable minimal code style checks

- HISTORY.md
- doc/optimizers.md
- include/ensmallen_bits/bigbatch_sgd/adaptive_stepsize.hpp
- include/ensmallen_bits/fw/proximal/proximal_impl.hpp
- tests/bigbatch_sgd_test.cpp
- tests/cne_test.cpp
- tests/quasi_hyperbolic_momentum_sgd_test.cpp
I noticed that the tests took a long time, so I investigated and found that the CNE test can take a really long time.  So, I switched it to optimize simpler functions.  Then, I checked to make sure that the test failure probability was low, and had to tune a couple tests.
But probably the more interesting thing I did here was that I noticed the `BigBatchSGD` test sometimes failed after taking a `NaN` step size.  After some investigation, I traced this down to the estimation of the curvature---when the step size gets really small, there is no noticeable different in the iterates, and so `arma::norm(iterate - lastIterate, 2) == 0`, and the curvature estimate divides by that.
Therefore, the solution I settled on was just to avoid step size decay in this situation by taking the curvature …
> Clean up tests (runtime and failure probability)

- include/ensmallen_bits/pso/pso.hpp
- include/ensmallen_bits/pso/pso_impl.hpp
Fix for issue reported in https://github.com/mlpack/ensmallen/issues/123.
> Fix PSO bound type

- include/ensmallen_bits/fw/atoms.hpp
- include/ensmallen_bits/fw/update_span.hpp
- include/ensmallen_bits/sdp/primal_dual_impl.hpp
use the fast solver; the default iterative refinement in solve() is an overkill in these cases
> use fast solve

- include/ensmallen_bits/function/arma_traits.hpp
- include/ensmallen_bits/sdp/lrsdp_function.hpp
- include/ensmallen_bits/sdp/sdp.hpp
These simple fixes make it easier for older code to work with ensmallen 2.x.  There's no functionality change (although `GetInitialPoint()` for `LRSDP` had a bug, and this fixes that).
> Minor compatibility fixes for ensmallen 1.x

- include/ensmallen.hpp
CMakeLists.txt enforces Armadillo 8.400, so for consistency we need to do that in `include/ensmallen.hpp` as well
https://github.com/mlpack/ensmallen/blob/master/CMakeLists.txt#L55
> ensure armadillo version check uses the same numbers as CMakeLists.txt

- CONTRIBUTING.md
- HISTORY.md
- rel/ensmallen-release.sh
I thought it would be useful to add the release process and scripts to do it automatically to this repository; that way, anyone can easily and quickly make a release, and I am not a bottleneck. :)
> Add release process and details to the repository

- rel/ensmallen-release.sh
When earlier commands fail, it might not be such a great idea to run later git commands which do things like tagging and pushing.
> best practice: set bash option to terminate shell upon expected error

- HISTORY.md
- include/ensmallen_bits/lbfgs/lbfgs_impl.hpp
While debugging some mlpack test failures I discovered that it is possible that `scalingFactor` for L-BFGS can be computed as `0.0` when the optimization is getting very close to convergence.  This, then, causes a division by 0 later on in the code, and the returned iterate goes to a bunch of NaN garbage.
So, this change addresses that by catching the case where the scaling factor is computed as 0, and terminates successfully in that case.
> Check L-BFGS scaling factor for convergence

- CMakeLists.txt
- COPYRIGHT.txt
- HISTORY.md
- README.md
According to `CMakeLists.txt`
> This project has no configurable options---it just installs the headers to the install location, and optionally builds the test program.
but it's not optional at the moment. This PR adds the option in CMake :smile:.
> Add optional test building

- doc/callbacks.md
- doc/function_types.md
- doc/optimizers.md
Handling : https://github.com/mlpack/ensmallen/issues/139
:rocket:  Done
> Collapsible code examples in documentation

- tests/callbacks_test.cpp
This patch fixes a compile-time warning and test case failure on
32-bit architectures, including i386.
cd /<<PKGBUILDDIR>>/obj-i686-linux-gnu/tests && /usr/bin/c++   -I/<<PKGBUILDDIR>>/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fopenmp -Wall -Wpedantic -Wunused-parameter   -std=gnu++11 -o CMakeFiles/ensmallen_tests.dir/cmaes_test.cpp.o -c /<<PKGBUILDDIR>>/tests/cmaes_test.cpp
/<<PKGBUILDDIR>>/tests/callbacks_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____46()’:
/<<PKGBUILDDIR>>/tests/callbacks_test.cpp:397:28: warning: unsigned conversion from ‘long long int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘10000000000’ to ‘1410065408’ [-Woverflow]
397 |   StandardSGD …
> 32-bit safety in big random number

- HISTORY.md
- include/ensmallen_bits/problems/ackley_function_impl.hpp
- include/ensmallen_bits/problems/beale_function_impl.hpp
- include/ensmallen_bits/problems/cross_in_tray_function_impl.hpp
- include/ensmallen_bits/problems/goldstein_price_function_impl.hpp
- include/ensmallen_bits/problems/himmelblau_function_impl.hpp
- include/ensmallen_bits/problems/holder_table_function_impl.hpp
- include/ensmallen_bits/problems/levy_function_n13_impl.hpp
- include/ensmallen_bits/problems/schaffer_function_n2_impl.hpp
- include/ensmallen_bits/problems/schaffer_function_n4_impl.hpp
- include/ensmallen_bits/problems/three_hump_camel_function_impl.hpp
- tests/pso_test.cpp
It made for a bit more `std::pow()`, `std::sin()`, etc., but anyway, now including anything in the `problems/` directory should not cause any problems for downstream code.  This fixes #146.
> Remove 'using namespace std' from problems.

- HISTORY.md
- doc/function_types.md
- doc/optimizers.md
- include/ensmallen.hpp
- include/ensmallen_bits/ada_bound/ada_bound.hpp
- include/ensmallen_bits/ada_bound/ada_bound_impl.hpp
- include/ensmallen_bits/ada_bound/ada_bound_update.hpp
- include/ensmallen_bits/ada_bound/ams_bound_update.hpp
- tests/CMakeLists.txt
- tests/ada_bound_test.cpp
Implementation of AdaBound and AMSBound which employ dynamic bounds on
learning rates to achieve a gradual and smooth transition from adaptive methods to
SGD. For more information see "Adaptive Gradient Methods with Dynamic Bound of Learning Rate" by Luo, Liangchen and Xiong, Yuanhao and Liu, Yan and Sun, Xu.
> AdaBound + AMSBound

- HISTORY.md
- doc/function_types.md
- doc/optimizers.md
- include/ensmallen.hpp
- include/ensmallen_bits/adam/optimisticadam_update.hpp
- include/ensmallen_bits/callbacks/progress_bar.hpp
- include/ensmallen_bits/callbacks/traits.hpp
- include/ensmallen_bits/de/de.hpp
- include/ensmallen_bits/eve/eve.hpp
- include/ensmallen_bits/function/traits.hpp
- include/ensmallen_bits/lookahead/lookahead.hpp
- include/ensmallen_bits/lookahead/lookahead_impl.hpp
- include/ensmallen_bits/parallel_sgd/parallel_sgd.hpp
- include/ensmallen_bits/pso/pso.hpp
- tests/CMakeLists.txt
- tests/lookahead_test.cpp
Implementation of "Lookahead Optimizer: k steps forward, 1 step back" by Michael R. Zhang, James Lucas, Geoffrey Hinton, Jimmy Ba.
> Lookahead Optimizer: k steps forward, 1 step back

- HISTORY.md
- include/ensmallen_bits/lookahead/lookahead.hpp
The builds fails (gcc 9.2.1), if the return type is wrong.
> Lookahead - Synchronization period type fix

- HISTORY.md
- tests/lbfgs_test.cpp
- tests/spsa_test.cpp
This comes out of the discussion of #142.  The issue being seen on some i386 tests is this:
```
-------------------------------------------------------------------------------
RosenbrockFunctionFloatTest
-------------------------------------------------------------------------------
/<<PKGBUILDDIR>>/tests/lbfgs_test.cpp:41
...............................................................................
/<<PKGBUILDDIR>>/tests/lbfgs_test.cpp:54: FAILED:
REQUIRE( coords(1) == Approx(1.0).epsilon(1e-7) )
with expansion:
1.0f == Approx( 1.0 )
```
This happens because the `epsilon()` is too small for `float`, and also it can't hurt to explicitly mark `1.0f` instead of `1.0`.  (However, that part's not totally necessary, so I only did it in a few places.)
> Fix float types and tolerances in some tests.

- HISTORY.md
- include/ensmallen_bits/ada_bound/ada_bound.hpp
- include/ensmallen_bits/ada_delta/ada_delta.hpp
- include/ensmallen_bits/ada_grad/ada_grad.hpp
- include/ensmallen_bits/adam/adam.hpp
- include/ensmallen_bits/ftml/ftml.hpp
- include/ensmallen_bits/padam/padam.hpp
- include/ensmallen_bits/qhadam/qhadam.hpp
- include/ensmallen_bits/rmsprop/rmsprop.hpp
- include/ensmallen_bits/smorms3/smorms3.hpp
- include/ensmallen_bits/swats/swats.hpp
- include/ensmallen_bits/wn_grad/wn_grad.hpp
- tests/callbacks_test.cpp
This allows a user to a Callback with:
```c++
Optimize(..., ProgressBar());
```
instead of:
```c++
ProgressBar cb;
Optimize(..., cb);
```
which I thought already worked, but it turns out it only worked for optimizers that aren't based on another one, e.g. the `Adam` optimizer uses `SGD` as basis.
> Fix Callback passing for SGD based optimizers.

- HISTORY.md
- include/ensmallen_bits/lookahead/lookahead.hpp
- include/ensmallen_bits/lookahead/lookahead_impl.hpp
In the previous version each optimizer passed to Lookahead had to implement `MaxIterations()`.
> Fix Lookahead MaxIterations() check

- include/ensmallen_bits/callbacks/callbacks.hpp
prevent spurious compiler warnings as experienced when compiling mlpack-master with gcc 7.4 on ubuntu 18.04
this makes more important compiler warnings + errors more visible during the compilation process
> prevent spurious compiler warnings

- HISTORY.md
- include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd.hpp
- include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd_impl.hpp
- include/ensmallen_bits/lookahead/lookahead.hpp
- include/ensmallen_bits/lookahead/lookahead_impl.hpp
- include/ensmallen_bits/pso/pso.hpp
- include/ensmallen_bits/pso/pso_impl.hpp
- include/ensmallen_bits/sdp/lrsdp_function.hpp
- include/ensmallen_bits/sdp/lrsdp_function_impl.hpp
- include/ensmallen_bits/sgd/sgd.hpp
- include/ensmallen_bits/sgd/sgd_impl.hpp
- include/ensmallen_bits/spalera_sgd/spalera_sgd.hpp
- include/ensmallen_bits/spalera_sgd/spalera_sgd_impl.hpp
- include/ensmallen_bits/svrg/svrg.hpp
- include/ensmallen_bits/svrg/svrg_impl.hpp
While using `valgrind` I noticed that the `instDecayPolicy` and `instUpdatePolicy` used by SGD actually aren't properly deallocated.  So this adds destructors to any optimizer that uses an `Any` internally, and that destructor calls `Clear()` to correctly free any allocated memory.
There are a few PRs now that have been merged since the last release, so I think we can do another release after this is merged.
> Fix memory leak

- .travis.yml
- HISTORY.md
This follows #171 and should hopefully fix the oversight for non pr-based tests
In doing so, I've made some other travis changes, and I'm not sure if they're desired.
> not-so-quick fix sanity check for outside of PRs

- doc/function_types.md
- doc/optimizers.md
- include/ensmallen_bits/sa/sa.hpp
- include/ensmallen_bits/sa/sa_impl.hpp
There are some examples in the documentation that can't be copy/pasted, which is either because we didn't use the correct syntax or because some of the parameters are missing.
> Example doc fix + add/use default argument.

- HISTORY.md
- README.md
This better matches the existing literature and is likely to be less confusing to people who come across the term.
See also mlpack/ensmallen.org#10, and the tech report we're about to submit where we used this term instead of 'mathematical optimization'.
> Change 'mathematical optimization' to 'numerical optimization'

- scripts/ensmallen-release.sh
- scripts/update-website-after-release.sh
I noticed in #185 that @favre49 wasn't able to push any extra commits during merge, and I ended up with a better understanding of Github branch protection permissions.  Anyway, what it means is that folks in the Contributors team can't push directly to `master` (and now, neither can I, I shouldn't have been able to to begin with given my propensity for typing before thinking :smile:), and so the release scripts have to be updated.
Here's the new idea for the workflow:
1. Anyone (actually even including folks not on the Contributors team) can run the `scripts/ensmallen-release.sh` script, like this:
```
$ scripts/ensmallen-release.sh rcurtin 2 13 0 "New Release Name"
```
(The Github username is necessary so that it's known where the fork is.)  This script will create a new branch in the …
> Update release scripts

- CMake/ensmallen-config.cmake.in
- CMakeLists.txt
- HISTORY.md
Just some minor fixes for cmake package export:
* Fix spelling mistake introduced in 369046f
* Don't export compiler warning flags to interface.
> Fix cmake package export.

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
- scripts/ensmallen-release.sh
This automatically-generated pull request adds the commits necessary to make the 2.13.0 release.
* Fix CMake package export ([#198](https://github.com/mlpack/ensmallen/pull/198)).
* Allow early stop callback to accept a lambda function ([#165](https://github.com/mlpack/ensmallen/pull/165)).
> Release version 2.13.0: "Automatically Automated Automation"

- HISTORY.md
- doc/function_types.md
- doc/optimizers.md
- include/ensmallen_bits/aug_lagrangian/aug_lagrangian_impl.hpp
- include/ensmallen_bits/lbfgs/lbfgs_impl.hpp
This solves #199. 
Our documentation for constrained functions is actually incorrect.  The documentation implies that both "hard" and "soft" constraints are supported but this is not true.  In fact, the augmented Lagrangian optimizer (the only constrained optimizer we currently have) requires "soft" (differentiable) constraints.  Although I think it would be useful to provide support for optimizers that can take in arbitrary constraints, at the moment we don't have any, so I thought it was best to just simplify the documentation.
Also I fixed an issue where the L-BFGS optimizer will return NaNs when the starting point gives a gradient that is 0.  Essentially, for some reason, we previously did not allow termination on the first iteration due to the gradient norm being too small.  That's …
> Fix constrained optimizer documentation

- HISTORY.md
- include/ensmallen_bits/aug_lagrangian/aug_lagrangian_impl.hpp
Finally, after far too long, I took some time to look into #142.  I was able to replicate the problem with the `Johnson844LovaszThetaFMatSDP` test.
The augmented Lagrangian optimizer (`AugLagrangian`) keeps a penalty parameter `sigma` internally.  This is stored as a `double`---but `Johnson844LovaszThetaFMatSDP` is a test that specifically uses `arma::fmat` as an objective matrix type (so, e.g., `float` is the element type).
`AugLagrangian` was also hard-coded to terminate on an absolute objective difference of `1e-10`---but for this particular test, the objective function converges to `-14`... and due to the precision afforded by `1e-14`, it's not actually possible to have two different `float`s very near `-14` that are less than `1e-10` apart!  So, I modified the tolerance to be based …
> Set AugLagrangian tolerance based on ElemType

- HISTORY.md
- scripts/ensmallen-release.sh
Fix release script to use CLI arguments instead of the hardcoded ones.
> Fix release script

- HISTORY.md
- scripts/ensmallen-release.sh
This is a simple change to correctly extract the changelog in the release script.  Previously, it would search for, e.g.,
```
```
but it needs to search for
```
```
You can see an example of the existing script failing in #218 and then the modified script succeeding in #219.
> Fix quotation bug in release script.

- HISTORY.md
- include/ensmallen_bits/problems/fonseca_fleming_function.hpp
Fixes the type issues that came up during a CRAN check submission on Solaris. 
> In file included from ../inst/include/ensmallen_bits/problems/problems.hpp:20:0,
>                  from ../inst/include/ensmallen.hpp:77,
>                  from ../inst/include/RcppEnsmallen.h:25,
>                  from RcppExports.cpp:4:
> ../inst/include/ensmallen_bits/problems/fonseca_fleming_function.hpp: In member function ‘typename MatType::elem_type ens::test::FonsecaFlemingFunction<MatType>::ObjectiveA::Evaluate(const MatType&)’:
> ../inst/include/ensmallen_bits/problems/fonseca_fleming_function.hpp:74:57: error: call of overloaded ‘sqrt(int)’ is ambiguous
>          return 1.0f - exp(-pow(coords[0] - 1.0f / sqrt(3), 2) -
> 
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/RcppEnsmallen …
> Fix implementation of fonesca fleming problem function f1 and f2     type usage and negative signs.

- HISTORY.md
- tests/ada_delta_test.cpp
- tests/ada_grad_test.cpp
This PR adapts the strategies used for the two tests (AdaDelta and AdaGrad) that use `SimpleSGDTestFunction` with an `arma::fmat`.  Basically I increased the step size and this seemed to help, but not enough, so I then made the test run a maximum of three times to make sure it converges at least once.  With these changes, now locally I saw no failures of either test with >1000 runs.
This should fix #182 and #225. :+1:
> Fix SimpleSGDTestFunction arma::fmat test failures

- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
- scripts/ensmallen-release.sh
From #222, we discussed adding date information to the header file for when ensmallen was released/updated. This PR includes the version update within `ens_version.hpp` and updates the release script to automatically set these fields.
> Incorporate release date with ensmallen version

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.15.0 release.
* Make a few tests more robust
([#228](https://github.com/mlpack/ensmallen/pull/228)).
* Add release date to version information. ([#226](https://github.com/mlpack/ensmallen/pull/226))
* Fix typo in release script
([#236](https://github.com/mlpack/ensmallen/pull/236)).
> Release version 2.15.0: "Why Can't I Manage To Grow Any Plants?"

- HISTORY.md
- include/ensmallen.hpp
While preparing the new CRAN release, my local compile on macOS 10.15.7 yielded an error when compiling of:
```bash
error: no template named 'HasStepSizeSignature' in namespace 'ens::traits';
did you mean 'HasBatchSizeSignature'?
```
I've verified that the definition is present in `traits`. 
Oddly enough, the new version is passing cleanly with CI checks: coatless/rcppensmallen#39 
I think the error is being triggered because of an include-order issue. Specifically, `ensmallen/include/ensmallen.hpp` needs to have `#include "ensmallen_bits/function.hpp"` placed before `#include "ensmallen_bits/callbacks/report.hpp"`
<details>
<summary>
Full stack trace
</summary>
```bash
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG …
```
> Fix include order of traits which reports depends upon

- HISTORY.md
- README.md
- example.cpp
This is to partially address the concerns raised by JMLR reviewer 1.
Specifically, the short example program has been added to satisfy the following comment:
> The documentation of ensmallen is detailed but I missed some simple examples in the README file. There are examples in the documentation, but I believe having a few compileable-then-runnable examples in the repository would be a great improvement.
> add short example program; expand README with example installation

- include/ensmallen_bits/callbacks/report.hpp
This fixes #246.
Basically, the `Report` callback was failing (segfaulting) when an optimizer took no steps at all.  These changes try to handle that a bit more gracefully, and print a warning for the user, since they may need to investigate why the optimizer took no steps.
> Fix Report callback when no steps were taken.

- HISTORY.md
- tests/parallel_sgd_test.cpp
I noticed this issue while testing. It seems to be a bug introduced by #249.  I guess the system I was testing on somehow did not set `ENS_USE_OPENMP`.
> Fix compilation issue when ENS_USE_OPENMP is specified.

- HISTORY.md
- include/ensmallen_bits/cne/cne_impl.hpp
- tests/main.cpp
This fixes #247.  I chose against multiplying the normal distribution by `mutationSize` because the documentation only says that it uses a `normal distribution` (e.g. variance 1).  I'm totally open to other strategies here; I don't have any particular opinion on what is best.
I also undid an accidental change from another PR, and commented out the random seed for each test run.
> Use normal distribution for CNE initial population generation

- HISTORY.md
- include/ensmallen_bits/problems/ackley_function.hpp
- include/ensmallen_bits/problems/beale_function.hpp
- include/ensmallen_bits/problems/booth_function.hpp
- include/ensmallen_bits/problems/bukin_function.hpp
- include/ensmallen_bits/problems/colville_function.hpp
- include/ensmallen_bits/problems/drop_wave_function.hpp
- include/ensmallen_bits/problems/easom_function.hpp
- include/ensmallen_bits/problems/eggholder_function.hpp
- include/ensmallen_bits/problems/generalized_rosenbrock_function.hpp
- include/ensmallen_bits/problems/goldstein_price_function.hpp
- include/ensmallen_bits/problems/gradient_descent_test_function.hpp
- include/ensmallen_bits/problems/levy_function_n13.hpp
- include/ensmallen_bits/problems/matyas_function.hpp
- include/ensmallen_bits/problems/mc_cormick_function.hpp
- include/ensmallen_bits/problems/rastrigin_function.hpp
- include/ensmallen_bits/problems/rosenbrock_function.hpp
- include/ensmallen_bits/problems/rosenbrock_wood_function.hpp
- include/ensmallen_bits/problems/schaffer_function_n2.hpp
- include/ensmallen_bits/problems/schwefel_function.hpp
- include/ensmallen_bits/problems/sgd_test_function.hpp
- include/ensmallen_bits/problems/sparse_test_function.hpp
- include/ensmallen_bits/problems/sphere_function.hpp
- include/ensmallen_bits/problems/styblinski_tang_function.hpp
- include/ensmallen_bits/problems/three_hump_camel_function.hpp
- include/ensmallen_bits/problems/wood_function.hpp
Another pretty simple PR.  It should fix many warnings that I see when I compile mlpack.
> Remove unused `const` to fix compilation warnings

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.16.1 release.
* Fix test compilation issue when `ENS_USE_OPENMP` is set ([#255](https://github.com/mlpack/ensmallen/pull/255)).
* Fix CNE initial population generation to use normal distribution ([#258](https://github.com/mlpack/ensmallen/pull/258)).
* Fix compilation warnings ([#259](https://github.com/mlpack/ensmallen/pull/259)).
> Release version 2.16.1: "Severely Dented Can Of Polyurethane"

- include/ensmallen_bits/nsga2/nsga2_impl.hpp
Hi @say4n , I've been reading your code on NSGA2 and I really like it :).  I've made some small corrections. 
- minor grammar fix
- replace std::endl with "\n"
> Nits on NSGA2

- include/ensmallen_bits/problems/schaffer_function_n1.hpp
Deceptively innocent but causes compile-time error when ```arma::fmat``` is used to collect initial point. Can we have a quick merge on this, please? @zoq
> SchafferN1 Initial Point fix

- HISTORY.md
- include/ensmallen_bits/problems/ackley_function.hpp
- include/ensmallen_bits/problems/beale_function.hpp
- include/ensmallen_bits/problems/booth_function.hpp
- include/ensmallen_bits/problems/bukin_function.hpp
- include/ensmallen_bits/problems/colville_function.hpp
- include/ensmallen_bits/problems/cross_in_tray_function.hpp
- include/ensmallen_bits/problems/drop_wave_function.hpp
- include/ensmallen_bits/problems/easom_function.hpp
- include/ensmallen_bits/problems/eggholder_function.hpp
- include/ensmallen_bits/problems/generalized_rosenbrock_function.hpp
- include/ensmallen_bits/problems/goldstein_price_function.hpp
- include/ensmallen_bits/problems/gradient_descent_test_function.hpp
- include/ensmallen_bits/problems/levy_function_n13.hpp
- include/ensmallen_bits/problems/matyas_function.hpp
- include/ensmallen_bits/problems/mc_cormick_function.hpp
- include/ensmallen_bits/problems/rastrigin_function.hpp
- include/ensmallen_bits/problems/rosenbrock_function.hpp
- include/ensmallen_bits/problems/rosenbrock_wood_function.hpp
- include/ensmallen_bits/problems/schaffer_function_n2.hpp
- include/ensmallen_bits/problems/schwefel_function.hpp
- include/ensmallen_bits/problems/sgd_test_function.hpp
- include/ensmallen_bits/problems/sparse_test_function.hpp
- include/ensmallen_bits/problems/sphere_function.hpp
- include/ensmallen_bits/problems/styblinski_tang_function.hpp
- include/ensmallen_bits/problems/three_hump_camel_function.hpp
- include/ensmallen_bits/problems/wood_function.hpp
In the discussion of #272 we realized it would be a good idea to add comments to each of the test problems that implement `GetInitialPoint()`, `GetFinalObjective()`, and `GetFinalPoint()`, in order to indicate that these are not necessary if you just want to optimize a function, and that these are only there just for the convenience of our testing infrastructure.
So, this PR just adds those comments, and moves those functions to the bottom of the class.
> Clarifying comments about test problems

- HISTORY.md
- tests/adam_test.cpp
Let's see if removing the approximation improves test stability.
> Remove AdamSchafferFunctionN2Test test case

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.16.2 release.
* Fix CNE test trials ([#267](https://github.com/mlpack/ensmallen/pull/267)).
* Update Catch2 to 2.13.4 ([#268](https://github.com/mlpack/ensmallen/pull/268)).
* Fix typos in documentation ([#270](https://github.com/mlpack/ensmallen/pull/270), [#271](https://github.com/mlpack/ensmallen/pull/271)).
* Add clarifying comments in problems/ implementations ([#276](https://github.com/mlpack/ensmallen/pull/276)).
> Release version 2.16.2: "Severely Dented Can Of Polyurethane"

- include/ensmallen_bits/fw/proximal/proximal_impl.hpp
- include/ensmallen_bits/pso/update_policies/lbest_update.hpp
- include/ensmallen_bits/sarah/sarah_impl.hpp
- include/ensmallen_bits/sgdr/snapshot_ensembles.hpp
- include/ensmallen_bits/spalera_sgd/spalera_stepsize.hpp
Some simple adjustments to make the code analyzer happy.
> Code analyzer adjustments

- HISTORY.md
- include/ensmallen_bits/function/static_checks.hpp
- include/ensmallen_bits/nsga2/nsga2_impl.hpp
Refer #282 Section II.
Is there a strong reason for having ```template<MatType, FunctionType>``` instead of ```template<FunctionType, MatType>```, the problem is when we do recursive call, I need the FunctionType to be the at the end for it to work. I don't see any other way.
Infact if we go by ```template<MatType, FunctionType>```, I can integrate ```CheckMultiArbitraryFunctionTypeAPI()``` into ```CheckArbitraryFunctionTypeAPI()```, and it will work like normal + MOO checks.
> Recursively check for Evaluate() in MOO

- .travis.yml
For some reason travis marks the build as failed (I guess it's because it can't download some packages), let's see if switching to an more up-t-date ubuntu solves the issue.
> Switch from Ubuntu Trusty 14.04 to Ubuntu Focal 20.04

- tests/main.cpp
Use Catch2 seed command-line argument to set ensmallen seeds; this enables us to improve the automatic test pipeline to run the tests multiple times with different random seeds.
> Use Catch2 seed command-line argument to set ensmallen seeds

- HISTORY.md
- doc/callbacks.md
- include/ensmallen.hpp
- include/ensmallen_bits/callbacks/callbacks.hpp
- include/ensmallen_bits/callbacks/query_front.hpp
- include/ensmallen_bits/callbacks/traits.hpp
- include/ensmallen_bits/nsga2/nsga2_impl.hpp
- tests/callbacks_test.cpp
Related to #282  
@zoq Let me know if you agree with this methodology. You can check the commit message to see what I've done.
> Make Callback flexible for MultiObjective Optimizers.

- HISTORY.md
- doc/optimizers.md
- include/ensmallen_bits/moead/moead.hpp
- include/ensmallen_bits/moead/weight_init_policies/dirichlet_init.hpp
- tests/moead_test.cpp
> Add Dirichlet Weight Initialization

- HISTORY.md
- README.md
Improved installation and compilation instructions:
* show how to install manually (in addition to cmake)
* show how to install with and without root access
* added example compilation commands, using standard and non-standard installation directories
> improved installation and compilation instructions

- HISTORY.md
- README.md
- tests/CMakeLists.txt
Disable building the tests by default, as discussed in https://github.com/mlpack/ensmallen/issues/301
Tests can still be optionally built.
Advantages: faster and easier installation by users.
> don't build tests by default

- HISTORY.md
- include/ensmallen_bits/nsga2/nsga2.hpp
- include/ensmallen_bits/nsga2/nsga2_impl.hpp
- tests/nsga2_test.cpp
This came out of the discussion for #303---to avoid breaking reverse compatibility, I re-added the `Front()` function to the `NSGA2` class.  Actually it turned out to be slightly more difficult than I thought: to match the API, we have to return a reference, so we actually needed to re-add a member to the `NSGA2` class.  But, that member is only populated if the user calls `Front()`.
Anyway, this can all be removed in the next major version release of ensmallen, but until then, anyone who happens to be using `Front()` from `NSGA2` should not have their code broken. :)
> Add Front() back into the NSGA2 class.

- HISTORY.md
- include/ensmallen_bits/problems/schwefel_function.hpp
- include/ensmallen_bits/sa/sa_impl.hpp
- include/ensmallen_bits/sdp/primal_dual_impl.hpp
Mainly to take into account changes in Armadillo 10.5, where matrices are by default constructed with all elements set to zero.
The changes in this PR are backwards compatible with earlier versions of Armadillo.
> various fixes for matrix initialisation

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.17.0 release.
* CheckArbitraryFunctionTypeAPI extended for MOO support ([#283](https://github.com/mlpack/ensmallen/pull/283)).
* Refactor NSGA2 ([#263](https://github.com/mlpack/ensmallen/pull/263), [#304](https://github.com/mlpack/ensmallen/pull/304)).
* Add Indicators for Multiobjective optimizers ([#285](https://github.com/mlpack/ensmallen/pull/285)).
* Make Callback flexible for MultiObjective Optimizers ([#289](https://github.com/mlpack/ensmallen/pull/289)).
* Add …
> Release version 2.17.0: "Pachis Din Me Pesa Double"

- CMakeLists.txt
- HISTORY.md
Remove the `BUILD_TESTS` option in favor of `make ensmallen_tests` see https://github.com/mlpack/ensmallen/pull/303 for more details.
> The BUILD_TESTS option was replaced with 'make ensmallen_tests'.

- .travis.yml
I'm currently configuring a Jenkins job to replace the travis build but in the meantime I figured we can still use the existing travis credits.
> Update travis config to build the ensmallen tests

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- HISTORY.md
- README.md
As discussed here https://github.com/mlpack/ensmallen/pull/315 we like to bump the minimum Armadillo version to 9.800. I think once merged we should do another release `2.18.0`.
> Bump minimum Armadillo version to 9.800.

- HISTORY.md
- doc/callbacks.md
- include/ensmallen.hpp
- include/ensmallen_bits/callbacks/grad_clip_by_norm.hpp
- include/ensmallen_bits/callbacks/grad_clip_by_value.hpp
- include/ensmallen_bits/callbacks/traits.hpp
- tests/callbacks_test.cpp
Writing a recurrent network test case where the gradient explodes, so implemented gradient clipping.
> GradClipByValue callback

- HISTORY.md
- include/ensmallen_bits/cmaes/cmaes_impl.hpp
if `BaseMatType` is `fmat` (ie. matrix with single precision elements), 1e-16 is effectively zero, leading to an infinite loop if `chol()` fails on the `C[idx0]` matrix.
The solution is to use type dependent epsilon.
> avoid infinite loop for single-precision matrices

- HISTORY.md
- tests/scd_test.cpp
Use the correct number of classes to generate the label vector. This will fix the build issue reported in https://github.com/mlpack/ensmallen/issues/329.
> SCD partial gradient test fix

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.18.1 release.
* Accelerate SGD test time ([#330](https://github.com/mlpack/ensmallen/pull/300)).
* Fix potential infinite loop in CMAES ([#331](https://github.com/mlpack/ensmallen/pull/331)).
* Fix SCD partial gradient test ([#332](https://github.com/mlpack/ensmallen/pull/332)).
> Release 2.18.1

- HISTORY.md
- include/ensmallen_bits/callbacks/progress_bar.hpp
Fix for https://github.com/mlpack/ensmallen/issues/244 now it shows the correct time in seconds:
```
Epoch 1/2
3/3 [====================================================================================================] 100% - 210s 70000ms/step - loss: 1224.1
Epoch 2/2
2/3 [==================================================================>.................................] 66% - ETA: 10s - loss: 439.535
```
See the `210s` at the end of the first epoch, which is the sum of each step.
> Report the correct epoch time in seconds.

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.18.2 release.
* Update Catch2 to 2.13.8 ([#336](https://github.com/mlpack/ensmallen/pull/336)).
* Fix epoch timing output ([#337](https://github.com/mlpack/ensmallen/pull/337)).
> Release version 2.18.2: "Fairmount Bagel"

- HISTORY.md
- tests/frankwolfe_test.cpp
- tests/line_search_test.cpp
- tests/sdp_primal_dual_test.cpp
`ARMA_DONT_PRINT_ERRORS` was originally added to prevent runtime warnings coming from `arma::eig_sym()` within the `CheckPositiveSemiDefinite()` function within tests/sdp_primal_dual_test.cpp.
Since Armadillo 10.4, `ARMA_DONT_PRINT_ERRORS` doesn't do anything, as failed decompositions no longer emit warnings by default.  (The warning level can be adjusted via `ARMA_WARN_LEVEL`.)
Since Armadillo 11.2+, a compile-time deprecation notice is emitted if `ARMA_DONT_PRINT_ERRORS` is defined.
Since Armadillo 11.2+, a compile-time deprecation notice is emitted if `operator<<` is used for matrix and vector initialisation.  The much more efficient C++11 initializer_lists can be used instead.
> avoid deprecation warnings in armadillo 11.2+

- doc/optimizers.md
This fixes #353, where the examples in the documentation used 2-dimensional bounds for `SchafferFunctionN1`, but `SchafferFunctionN1` optimizes only a one-dimensional iterate.
I also changed `Front()` to `ParetoFront()` to ensure that the example code compiles.
> Fix dimensionality of bounds for uses of SchafferFunctionN1

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.19.1 release.
* Avoid deprecation warnings in Armadillo 11.2+ ([#347](https://github.com/mlpack/ensmallen/pull/347)).
> Release version 2.19.1: "Eight Ball Deluxe"

- HISTORY.md
- tests/cne_test.cpp
- tests/main.cpp
In #359 it was pointed out that the `CNEHimmelblauFunctionTest` was failing on i386.  I investigated by running it (on x86_64) with tons of different random seeds, and found it failed about once every 80 or 90 runs.  So I adjusted the tolerances accordingly.
I also followed @conradsnicta's suggestion to print the random seed when running the tests.  (It can be set from the command-line with the `--rng-seed` option.)
> Fix CNE test tolerances

- README.md
Add example optimisers to increase relevant keywords.
This increases the likelihood of ensmallen being found via web search (eg. users typing specific keywords into google).
The corresponding PR for ensmallen.org is at https://github.com/mlpack/ensmallen.org/pull/15
> add short list of example optimisers

- HISTORY.md
- include/ensmallen_bits/lbfgs/lbfgs_impl.hpp
> LBFGS: avoid generation of NaNs, and add checks for finite values

- include/ensmallen_bits/config.hpp
TLDR; Undefine conflicting 'As' macro which interferes with ensmallen. This stems from https://github.com/mlpack/mlpack/issues/3501
Long story:  
Class Library for Numbers (CLN; https://www.ginac.de/CLN/) is used by several other projects for scientific computing.  With infinite wisdom, CLN defines a conflicting "As" macro.  This prevents ensmallen (and hence mlpack) from being used in conjunction with CLN or any other project that uses CLN.
The proper fix would be to correct the CLN source.  However, CLN has been around for a long while, and various old versions are vendored inside many projects and distributed in many linux distros.  Undefining the silly "As" macro handles old versions of CLN.
Offending code is on lines 269 and 274 in …
> undefine conflicting As macro

- HISTORY.md
- doc/optimizers.md
- include/ensmallen_bits/cmaes/cmaes.hpp
- include/ensmallen_bits/cmaes/cmaes_impl.hpp
- include/ensmallen_bits/cmaes/transformation_policies/boundary_box_constraint.hpp
- include/ensmallen_bits/cmaes/transformation_policies/empty_transformation.hpp
- include/ensmallen_bits/nsga2/nsga2_impl.hpp
- include/ensmallen_bits/problems/zdt/zdt4_function.hpp
- tests/callbacks_test.cpp
- tests/cmaes_test.cpp
I've attempted to fix the inconsistencies listed out in issue #70 with a couple of other things:
1. I noticed that this implementation of CMAES does not handle parameters (decision variables) that are represented differently, in a similar fashion. More specifically, parameters that are represented as a column vector are treated differently from the SAME parameters that are represented as a row vector (with appropriate changes in the fitness/loss function of course).  That is to say, if there existed `P_row` and `P_col` (which are equivalent except in the form that they are represented in) and `L_row` and `L_col` (which are respective fitness functions where `L_row(P_row) =  L_col(P_col)`), they do not converge to the same result with the current implementation of CMAES. This wasn't very …
> An attempt to fix the current CMAES inconsistencies

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.20.0 release.
* Implementation of Active CMAES ([#367](https://github.com/mlpack/ensmallen/pull/367)).
* LBFGS: avoid generation of NaNs, and add checks for finite values ([#368](https://github.com/mlpack/ensmallen/pull/368)).
* Fix CNE test tolerances ([#360](https://github.com/mlpack/ensmallen/pull/360)).
* Rename `SCD` optimizer, to `CD` ([#379](https://github.com/mlpack/ensmallen/pull/379)).
> Release version 2.20.0: "Stripped Bolt Head"

- HISTORY.md
- include/ensmallen_bits/callbacks/report.hpp
Pretty simple change... before:
```
Optimization Report
--------------------------------------------------------------------------------
Initial coordinates: 
0.0000  0.0000  0.0000 ...
0.0000 
Final coordinates: 
-2.3592 -0.0324 -0.0261 ...
-0.1400 iter          loss          loss change   |gradient|    step size     total time    
0             0.883         0.000         4.532         0.010         0.007         
10            0.762         0.121         0.000         0.010         0.078         
20            1.195         -0.433        867.404       0.010         0.136         
30            0.627         0.567         0.104         0.010         0.200         
40            0.660         -0.033        55.468        0.010         0.261         
50            0.733         -0.074 …
```
> Add a newline after printing coordinates to `Report` callback

- HISTORY.md
- include/ensmallen_bits/aug_lagrangian/aug_lagrangian_impl.hpp
- include/ensmallen_bits/callbacks/query_front.hpp
- include/ensmallen_bits/cmaes/not_empty_transformation.hpp
- include/ensmallen_bits/lbfgs/lbfgs_impl.hpp
While investigating #390, I came across an interesting finding: L-BFGS was computing negative scaling values for the Hessian scaling step.  (These should not be negative!)  Specifically, the gradient norm was being computed as *negative* and this then snowballed into a convergence issue.  As it turns out, the convergence issue only seems to manifest on non-x86_64 architectures when using `arma::fmat` likely due to numerical precision specifics and other things along those lines.  Here's an example run of the `Johnson844LovaszThetaFMatSDP` test, printing negative gradient norms:
```
$ ./ensmallen_tests Johnson844LovaszThetaFMatSDP
ensmallen version: 2.21.0 (Bent Antenna)
armadillo version: 9.800.1 (Horizon Scraper)
random seed: 0
Filters: Johnson844LovaszThetaFMatSDP
Scaling factor less …
```
> Fix negative scaling factors for L-BFGS

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.21.1 release.
* Fix numerical precision issues for small-gradient L-BFGS scaling factor computations ([#392](https://github.com/mlpack/ensmallen/pull/392)).
* Ensure the tests are built with optimisation enabled ([#394](https://github.com/mlpack/ensmallen/pull/394)).
> Release version 2.21.1: "Bent Antenna"

- CMakeLists.txt
- HISTORY.md
- README.md
- include/ensmallen.hpp
- include/ensmallen_bits/config.hpp
- include/ensmallen_bits/function/sfinae_utility.hpp
- include/ensmallen_bits/nsga2/nsga2.hpp
Update C++ standard to C++14.
mlpack 4.4 already requires C++17, and Armadillo 14.0 will use C++14.
The only OS that required C++11 is RHEL 7 / CentOS 7, which is EOL as of 30 June 2024:
* https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux
* https://www.redhat.com/en/topics/linux/centos-linux-eol
* https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
Using "two most recent releases of long term Linux distros" as the yardstick for compiler support.  The Linux distros are: RHEL (+ clones like Rocky Linux and Alma Linux), Ubuntu LTS, and Debian.
The current two supported releases of RHEL (8 and 9), Ubuntu LTS (22.04 and 24.04), Debian (11 and 12) all provide GCC versions that support at least C++14.
RHEL 8 does not support C++17 properly, so not …
> update to C++14 standard

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- HISTORY.md
- include/ensmallen.hpp
- include/ensmallen_bits/function/arma_traits.hpp
- include/ensmallen_bits/utility/arma_traits.hpp
- tests/ada_bound_test.cpp
- tests/adam_test.cpp
- tests/bigbatch_sgd_test.cpp
- tests/eve_test.cpp
- tests/katyusha_test.cpp
- tests/rmsprop_test.cpp
- tests/sarah_test.cpp
- tests/sgdr_test.cpp
- tests/snapshot_ensembles.cpp
- tests/svrg_test.cpp
- tests/swats_test.cpp
Bump minimum Armadillo version to 10.8.2.
This allows using the numerous Armadillo API additions and enhancements since 9.800.  It also allows assuming throughout the ensmallen codebase that matrices are initialised to zero by default.
Current state of Armadillo versions in various distros:
- Ubuntu 22.04 LTS has Armadillo 10.8.2
- Ubuntu 24.04 LTS has Armadillo 12.6.7
- Debian 12 has Armadillo 11.4.2
- Debian 13 (testing) has Armadillo 12.8.2
- RHEL EPEL 8 & 9 has Armadillo 12.6.6 (subject to future upgrades)
Related: https://github.com/mlpack/mlpack/pull/3760
> Bump minimum Armadillo version to 10.8

- .github/workflows/auto-approve.yml
- .github/workflows/stale.yml
- .github/workflows/stickers.yml
This adds three Github actions that replace the functionality of the poor departed mlpack-bot:
* Auto-approval of a PR after 24 hours
* Stale issues/PR closure
* Post a message to new contributors that they can have stickers
These are the same as what the mlpack/mlpack repository uses.
> Add actions to replace mlpack-bot

- include/ensmallen_bits/agemoea/agemoea_impl.hpp
This PR is to fix the drift seen in AGEMOEA for highly convex functions(eg MAF3)
> AGEMOEA for Convex Fronts

- HISTORY.md
- include/ensmallen_bits/fw/atoms.hpp
- include/ensmallen_bits/fw/constr_lpball.hpp
Building `mlpack` under R using (Rcpp)Armadillo 14.2.0-1 leads to deprecation warnings which e.g. CRAN nags about.  The warnings start with the index minimum call in `atoms.hpp`; the change addresses and `ensmallen` (or rather `RcppEnsmallen`) still tests fine with it.  The second change is only other case I found with a quick search, there may be more.
> Armadillo 14.2.0 deprecation changes to (index) .min() and .max()

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.22.0 release.
* Update to C++14 standard ([#400](https://github.com/mlpack/ensmallen/pull/400)).
* Bump minimum Armadillo version to 10.8 ([#404](https://github.com/mlpack/ensmallen/pull/404)).
* For Armadillo 14.2.0 switch to `.index_min()` and `.index_max()` ([#409](https://github.com/mlpack/ensmallen/pull/409)).
* Added IPOP and BIPOP restart mechanisms for CMA-ES. ([#403](https://github.com/mlpack/ensmallen/pull/403)).
> Release version 2.22.0: "E-Bike Excitement"

- CMakeLists.txt
- HISTORY.md
I noticed that there was not a line in HISTORY.md for #413, so I added one.  (This will mean that the changelog won't be empty when I open a PR to release 2.22.1 with that fix.)
> Add an entry in the HISTORY for #413

- CONTRIBUTING.md
- HISTORY.md
- include/ensmallen_bits/ens_version.hpp
This automatically-generated pull request adds the commits necessary to make the 2.22.1 release.
* Remove unused variables to fix compiler warnings ([#413](https://github.com/mlpack/ensmallen/pull/413)).
> Release version 2.22.1: "E-Bike Excitement"

- README.md
Just a little cleanup---I noticed this morning that this is not listed.
> List minimum Armadillo version in README

- HISTORY.md
- doc/optimizers.md
- include/ensmallen_bits/bigbatch_sgd/bigbatch_sgd_impl.hpp
- include/ensmallen_bits/eve/eve_impl.hpp
- include/ensmallen_bits/sgd/sgd_impl.hpp
- include/ensmallen_bits/spalera_sgd/spalera_sgd_impl.hpp
I noticed while working with RNNs in mlpack that the estimated objective would be 0 if I was training sequences of different length one iteration at a time... digging into it, I discovered that any time you optimize a separable function with SGD-like optimizers and the number of iterations you use is an exact multiple of the number of functions (e.g. number of sequences given to the RNN), then the returned objective estimate is 0 unless you specify `exactObjective`.
This is because the objective estimate gets reset after every epoch, but if it is the last epoch... it still resets it anyway, it doesn't return the estimate.
So I fixed that for all optimizers I could find that had the condition, and then I updated the documentation to be a little clearer about what *does* get returned for …
> Don't reset the objective estimate on the last iteration

- HISTORY.md
- tests/de_test.cpp
Fix include statement to be consistent with other tests.
This is to resolve the following bug:
> include path
> The C++ test files must #include <ensmallen.hpp>
> rather than "../include/ensmallen.hpp"
> in order to allow the installed files, rather than the repo-local files, to be tested.
> 
> https://sources.debian.org/src/ensmallen/2.22.1-1/debian/patches/0001-include-path.patch/
@rcurtin @shrit @zoq @barak @eddelbuettel
> fix include

- HISTORY.md
- tests/demon_sgd_test.cpp
Increase tolerance for tests failing on 32 bit armel and armhf, aiming to address bug report #418.
PS. The form `Approx(x).epsilon(y)` as used by ensmallen tests is deprecated by Catch2, as it has several problems. The corresponding docs suggest to use `WithinAbs()` and `WithinRel`, as `Approx()` cannot be fixed without breaking backwards compatibility.  This would require rewriting all of the tests in ensmallen, which is beyond the scope of this PR.
https://github.com/catchorg/Catch2/blob/devel/docs/comparing-floating-point-numbers.md#top
@rcurtin @shrit @zoq @barak @eddelbuettel
> increase tolerance

- CMakeLists.txt
CRAN had actually come knocking a few weeks ago for another (small) project where I had (inherited from upstream) a similar `cmake` version range that the newer (and then unreleased, now it is out) version 4.0.* barked over.
Picking 3.5..4.0 appears to be a reasonable compromise as 3.5 is both sufficient ancient yet still suitable.  Beginning the interval with something older than 3.5 is apparently recommended against by the Kitware folks if I recall correctly.
> Set cmake version range to 3.5..4.0 which accommodates newer 4.0

- doc/callbacks.md
- include/ensmallen_bits/callbacks/timer_stop.hpp
While preparing the answer for #3992, I noticed that the callback documentation didn't point out anything about the `StepTaken()` function, and the `TimerStop` callback wasn't documented at all.  I overhauled the documentation to organize it a bit better, added documentation for `StepTaken()` and `TimerStop`, and reorganized things to hopefully be more useful to users.
> Overhaul documentation for callbacks.
